@startuml
:Палка: --> (Двигаться)
:Палка: --> (Поймать бонус)
:Палка: --> (Самоуничтожиться)


:Шарик: --> (Отскочить)
:Шарик: --> (Нанести урон кубику)


:Кубик: --> (Выбросить бонус)
:Кубик: --> (Получить урон)


:Бонус: --> (Изменить размер объекта)
:Бонус: --> (Дать палке возможность стрелять)
:Бонус: --> (Создать еще один шарик)

:Изменить размер объекта: <|-- (Уменьшить палку в размере)
:Изменить размер объекта: <|-- (Уменьшить шарик в размере)

:Получить урон: <|-- (Самоуничтожиться)

:Двигаться: <|-- (Двигаться влево)
:Двигаться: <|-- (Двигаться право)

:Отскочить: <|-- (Отскочить от стенки)
:Отскочить: <|-- (Отскочить от кубика)
:Отскочить: <|-- (Отскочить от палки)

@enduml
